# Welcome to Jekyll, plus changes by jenwr!
#
# Seriously, add some context, please. 

# Site settings
title: hi - PRINT IT
email: jen@domain.com - tbd
description: > # this means to ignore newlines until "baseurl:"
> #  A collection of seemingly disconnected ideas brought together to create something new and satisfying.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username:
# github_username:  
Thank you jekyll. 
# Build settings
markdown: kramdown
